config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  root 'transactions#index'
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
  end

  def new
    @transaction = Transaction.new
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = Transaction.new(transaction_params)

    if @transaction.save
        redirect_to @transaction
    else
        render 'new'
    end
  end

  private

  def transaction_params
        params.require(:transaction).permit(:car_type, :price, :first_vist, :bed_down, :mud_in_bed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transactions/index.html.erb
<%= link_to "Create New Transaction", new_transaction_path %>

<% @transactions.each_with_index do |transaction, index| %>
    <h2>Transaction <%= index + 1 %></h2>
    <div>Car Type: <%= transaction.car_type %></div>
    <div>Price: <%= transaction.price %></div>
    <div>First Visit: <%= transaction.first_visit %></div>
    <div>Bed Down: <%= transaction.bed_down %></div>
    <div>Mud in Bed: <%= transaction.mud_in_bed %></div>
    <%= link_to "See Transaction", transaction %>
<% end %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>


<%= form_for @transaction do |f| %>
    <%= f.label :car_type %><br>
    <%= f.text_field :car_type %><br>
    <br>
    <%= f.label :first_visit %><br>
    <%= f.check_box :first_visit %><br>
    <br>
    <%= f.label :bed_down %><br>
    <%= f.check_box :bed_down %><br>
    <br>
    <%= f.label :mud_in_bed %><br>
    <%= f.check_box :mud_in_bed %><br>
    <br>
    <div>Overall Price: </div>
    <br>
    <%= f.submit %>
<% end %>

app/views/transactions/show.html.erb
<h1><%= @transaction.car_type %> Transaction</h1>

<div>First Visit? <%= @transaction.first_visit %></div>
<br>
<div>Bed Down? <%= @transaction.bed_down %></div>
<br>
<div>Mud in Bed? <%= @transaction.mud_in_bed %></div>
<br>
<div>Overall Price: <%= @transaction.price %></div>